CREATE TABLE boards (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  path VARCHAR(16) NOT NULL,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(1024) NULL,
  flag_hidden BOOLEAN NOT NULL DEFAULT false,
  flag_nsfw BOOLEAN NOT NULL DEFAULT false
);

INSERT INTO boards (path, name, description, flag_hidden, flag_nsfw)
VALUES
  ('b', 'random', 'random stuff', false, true),
  ('a', 'anime', 'weeb stuff', false, false),
  ('int', 'international', 'chitchat around the globe', false, false)
;

CREATE TABLE anons (
  ipv4_addr INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  timestamp_created_thread TIMESTAMP NOT NULL DEFAULT DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY),
  timestamp_created_post TIMESTAMP NOT NULL DEFAULT DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY),
  timestamp_created_report TIMESTAMP NOT NULL DEFAULT DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)
);

CREATE TABLE posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  board_id INT UNSIGNED NOT NULL,
  thread_id INT UNSIGNED NULL DEFAULT NULL,
  data_message VARCHAR(4096) NOT NULL,
  data_filepath VARCHAR(1024) NULL DEFAULT NULL,
  data_thumbpath VARCHAR(1024) NULL DEFAULT NULL,
  datetime_created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  timestamp_edited TIMESTAMP NULL DEFAULT NULL,
  timestamp_bumped TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  ipv4_addr INT UNSIGNED NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  delete_reason VARCHAR(1024) NULL DEFAULT NULL,
  FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE,
  FOREIGN KEY (thread_id) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (ipv4_addr) REFERENCES anons(ipv4_addr) ON DELETE CASCADE
);

-- NOTE: requires event_scheduler=ON configuration
CREATE EVENT AutoDeleteOldPosts
ON SCHEDULE EVERY 1 DAY STARTS CURRENT_TIMESTAMP
DO
  DELETE LOW_PRIORITY
  FROM posts
  WHERE
    thread_id IS NULL
  AND
    datetime_created < DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 MONTH)
;

CREATE TABLE reports (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  post_id INT UNSIGNED NOT NULL,
  data_reason VARCHAR(1024) NOT NULL,
  datetime_created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  timestamp_processed TIMESTAMP NULL DEFAULT NULL,
  ipv4_addr INT UNSIGNED NOT NULL,
  processed BOOLEAN NOT NULL DEFAULT false,
  admin_notes VARCHAR(1024) NULL DEFAULT NULL,
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (ipv4_addr) REFERENCES anons(ipv4_addr) ON DELETE CASCADE
);

CREATE TABLE bans (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  report_id INT UNSIGNED NULL DEFAULT NULL,
  post_id INT UNSIGNED NULL DEFAULT NULL,
  data_reason VARCHAR(1024) NOT NULL,
  datetime_created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  datetime_starts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  datetime_ends DATETIME NULL DEFAULT NULL,
  ipv4_addr INT UNSIGNED NOT NULL,
  banned_ipv4_addr INT UNSIGNED NOT NULL,
  FOREIGN KEY (ipv4_addr) REFERENCES anons(ipv4_addr),
  FOREIGN KEY (banned_ipv4_addr) REFERENCES anons(ipv4_addr)
);

-- NOTE: requires event_scheduler=ON configuration
CREATE EVENT AutoDeleteExpiredBans
ON SCHEDULE EVERY 1 HOUR STARTS CURRENT_TIMESTAMP
DO
  DELETE LOW_PRIORITY
  FROM bans
  WHERE
    datetime_ends <= CURRENT_TIMESTAMP
;
