dist: xenial
language: python
python:
  - "3.7"
addons:
  mariadb: '10.4'
install:
  - pip install -r ./services/web/requirements.txt
  - sudo mysql < ./services/db/initdb.sql
script:
  - ./run_tests.sh
