dist: xenial
language: python
python:
  - "3.7"
addons:
  mariadb: '10.4'
install:
  # install tools
  - wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/6.5.5/flyway-commandline-6.5.5-linux-x64.tar.gz | tar xvz && sudo ln -s `pwd`/flyway-6.5.5/flyway /usr/local/bin
  # install python deps
  - pip install -r ./services/web/requirements.txt
  - pip install pytest-cov
  # setup db users
  - sudo mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root');"
  - sudo mysql -u root -e "select user,host,password from mysql.user;"
  # initialize integration test db
  - sudo mysql --user="root" --password="root" < ./services/db/initdb.sql
script:
  - sudo flyway -configFiles=./deployment/local/flyway.conf -connectRetries=15 migrate
  - python -m pytest --cov-report term --cov-report html --cov=services/web/api --cov=services/web/common --cov=services/web/thumb services/web/test/ -v
