version: '3.1'

services:
  # user = root/root
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  db-adminui:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
