AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lautasofta-service SAM template

Parameters:
  DbHost:
    Type: String
    Default: localhost
  DbUser:
    Type: String
    Default: root
  DbPasswd:
    Type: String
    Default: root
  DbName:
    Type: String
    Default: lautasofta
  MediaBucketName:
    Type: String
    Default: lautasofta-local-media
  S3EndpointUrl:
    Type: String
    Default: http://localhost:4566
  AdminIps:
    Type: String
    Default: '127.0.0.1'
  ApiDomainName:
    Type: String
    Default: ''
  ApiHostedZoneId:
    Type: String
    Default: ''
  ApiCertificateArn:
    Type: String
    Default: ''

Resources:
  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
  MediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MediaBucketName
      CorsConfiguration:
        CorsRules:
          - Id: AllowAnyOrigin
            MaxAge: '3600'
            AllowedOrigins: ['*']
            AllowedHeaders: ['*']
            AllowedMethods: ['GET', 'POST']
      # NOTE: check database/migrations/V1__init_db.sql::AutoDeleteOldPosts
      LifecycleConfiguration:
        Rules:
          - Id: ExpireObjects
            Status: 'Enabled'
            ExpirationInDays: 30
      LoggingConfiguration:
        DestinationBucketName: !Ref LogsBucket
        LogFilePrefix: 'access-logs/'
  ApiEndpoint:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Domain:
        DomainName: !Ref ApiDomainName
        CertificateArn: !Ref ApiCertificateArn
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: !Ref ApiHostedZoneId
  ApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: service/
      Handler: api.app.lambda_handler
      Runtime: python3.7
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          DB_HOST:          !Ref DbHost
          DB_USER:          !Ref DbUser
          DB_PASSWD:        !Ref DbPasswd
          DB_NAME:          !Ref DbName
          MEDIA_BUCKET:     !Ref MediaBucketName
          S3_ENDPOINT_URL:  !Ref S3EndpointUrl
          ADMIN_IPS:        !Ref AdminIps
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:PutObject'
                - 's3:PutObjectAcl'
                - 's3:DeleteObject'
              Resource: !Sub 'arn:aws:s3:::${MediaBucketName}/*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiEndpoint
  ThumbnailHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: service/
      Handler: thumb.app.lambda_handler
      Runtime: python3.7
      Timeout: 10
      MemorySize: 256
      Environment:
        Variables:
          DB_HOST:          !Ref DbHost
          DB_USER:          !Ref DbUser
          DB_PASSWD:        !Ref DbPasswd
          DB_NAME:          !Ref DbName
          MEDIA_BUCKET:     !Ref MediaBucketName
          S3_ENDPOINT_URL:  !Ref S3EndpointUrl
          ADMIN_IPS:        !Ref AdminIps
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
                - 's3:PutObjectAcl'
              Resource: !Sub 'arn:aws:s3:::${MediaBucketName}/*'
      Events:
        CreateThumbnailEvent:
          Type: S3
          Properties:
            Bucket: !Ref MediaBucket
            Events:
              - 's3:ObjectCreated:Post'
