AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lautasofta-service SAM template

Parameters:
  DbHost:
    Type: String
    Default: localhost
  DbUser:
    Type: String
    Default: root
  DbPasswd:
    Type: String
    Default: root
  DbName:
    Type: String
    Default: lautasofta
  MediaBucketName:
    Type: String
    Default: lautasofta-local-media
  S3EndpointUrl:
    Type: String
    Default: http://localhost:4572

Resources:
  MediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MediaBucketName
      LifecycleConfiguration:
        Rules:
          - Id: ExpireObjects
            Status: 'Enabled'
            ExpirationInDays: 30
  ApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: service/
      Handler: api.app.lambda_handler
      Runtime: python3.8
      Timeout: 3
      Environment:
        Variables:
          DB_HOST:          !Ref DbHost
          DB_USER:          !Ref DbUser
          DB_PASSWD:        !Ref DbPasswd
          DB_NAME:          !Ref DbName
          MEDIA_BUCKET:     !Ref MediaBucket
          S3_ENDPOINT_URL:  !Ref S3EndpointUrl
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
